version: "3.9"

volumes:
  mongo_data: {}
  registry_data: {}

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  frontend:
    image: lforchini/frontend
    build:
      context: ./
      dockerfile: client/Dockerfile

  backend:
    image: lforchini/backend
    build:
      context: ./
      dockerfile: server/Dockerfile
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  static:
    image: lforchini/static
    build:
      context: static
      dockerfile: Dockerfile

  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      # REGISTRY_HTTP_ADDR: 0.0.0.0:443
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/lforchini_com.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/lforchini_com.key
    restart: unless-stopped
    volumes:
      - registry_data:/data
      - /var/www/auth:/auth
      # - /var/www/certs:/certs 

  router:
    image: lforchini/router
    build:
      context: ./router
      dockerfile: Dockerfile
    volumes:
      - /var/www/certs/:/var/www/certs/
    ports:
      - 443:443
    depends_on:
      - frontend
      - backend
      - static
      - registry